### ISSUE TITLE
Make your documentation cleaner

### ISSUE THREAD

**Issue by alex-berliner** [BrettefromNesUniverse/patchlib#3]
Hi there, your project is very cool but I have to say that I inadvertently spent a lot of time trying to use features of it that I didn't realize weren't implemented due to the verbosity of your documentation.

- For bps, the very important piece of information that the `build()` function isn't implemented is only mentioned 3/4ths the way down the page after a bunch of information that is indeed interesting, but not useful for people looking to just use your library
- The `makepatch()` function is mentioned but not made clear that it's a helper function that doesn't exist in the library
- Usage instructions are generally not separated from the library's code analysis

I bring this up since this library is on PyPI and others may encounter the same issue as I have.

Thanks!

**Comment by brette-0** [comment]
Thanks for leaving this review, I'll revise ny documentation and adjust in response to your concerns separating traditional usage from advanced case documentation. However I would note that, notably with bps, the script doesn't intend to mimic existing tools but provide all possible conceivably useful tools for manipulating patch filetypes. Nevertheless I will improve the docs!

**Comment by brette-0** [comment]
Hello @alex-berliner, sorry for the delay in an actual response. I believe you may benefit more from [package docs](https://github.com/brette-0/patchlib/blob/main/docs/package_docs/patchlib.bps_docs.md) rather than the filetype docs.

As of writing my code BPS documentation was rather inaccessible and any verbosity would come as artifact of how I myself was very much learning while writing this. For future reference, filetype docs are in-depth documentation on how the file works, whereas package-docs are how to use my modules themselves.

However I do agree that filetype docs are a little untidy, this project has remained very quiet so cleaning up docs are by far not my most pressing matter. I hope this message brings some clarity 👍
